export {default as Registration} from './Registration/Registration'
export {default as SignIn} from './Sign_in/Sign_in';
export {default as Events} from './Events/Events';
export {default as Events_paper_p} from './Events_paper_p/Events_paper_p';
export {default as Home} from './Home/Home'
export {default as Events_Project} from './Events_Project/Events_Project';
export {default as Events_Frame} from './Events_Frame/Events_Frame';
export {default as Events_Treasure} from './Events_Treasure/Events_Treasure';
export {default as Events_Circuit} from './Events_Circuit/Events_Circuit';
export {default as Events_photon} from './Events_photon/Events_photon';
export {default as Contact} from './Contact/Contact';
export {default as Description} from './Description/Description';
export {default as Flash} from './Description/Flash';
export {default as Cine} from './Description/Cine';
export {default as Colloquium} from './Description/Colloquium';
export {default as Dialux} from './Description/Dialux';
export {default as Meta} from './Description/Meta';
export {default as Projectexpo} from './Description/Projectexpo';
export {default as Robo} from './Description/Robo';
export {default as Sherlock} from './Description/Sherlock';
export {default as Snakes} from './Description/Snakes';
export {default as Tycoon} from './Description/Tycoon';
export {default as Error} from './Description/Error';
export {default as Scavenger} from './Description/Scavenger';

export {default as Workshop} from './Workshop/Workshop';

export {default as Accomodation} from './Accomodation/Accomodation';
export {default as Payment} from './Payment/Payment';
export {default as Teams} from './Teams/Teams';
