export {default as Events} from './Events/Events';
export {default as Events_paper_p} from './Events_paper_p/Events_paper_p';
export {default as Home} from './Home/Home'
export {default as Events_Project} from './Events_Project/Events_Project';
export {default as Events_Frame} from './Events_Frame/Events_Frame';
export {default as Events_Treasure} from './Events_Treasure/Events_Treasure';
export {default as Events_Circuit} from './Events_Circuit/Events_Circuit';
export {default as Events_photon} from './Events_photon/Events_photon';
export {default as Contact} from './Contact/Contact';
export {default as Description} from './Description/Description';
export {default as EventTwo_des} from './EventTwo_des/EventTwo_des';
export {default as Accomodation} from './Accomodation/Accomodation';
export {default as Payment} from './Payment/Payment';